apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator-3
  annotations:
    scaler/state-peak-replicas: "5"
    scaler/state-bau-replicas: "2"
    scaler/state-default-replicas: "1"
  labels:
    app: random-generator-3
    scaler/opt-in: "false"
spec:
  selector:
    matchLabels:
      app: random-generator-3
  template:
    metadata:
      labels:
        app: random-generator-3
    spec:
      containers:
        - name: random-generator
          imagePullPolicy: Always
          image: chriscmsoft/random-generator:latest
